config/routes.rb
Roadtrip::Application.routes.draw do

  get "info/shoutouts"

  get "sessions/create"

  get "sessions/destroy"

  root :to => "sessions#new"

  match "shout-outs", :to => "info#shoutouts", :as => "shoutouts"

  resource :escape_picker, :controller => "escape_picker", :path => "escape_picker", :only => [:create]

  resources :songs, :only => :index
  resources :escapes, :only => [:index, :show, :update]

  match "auth/linkedin/callback", :to => "sessions#create"

  match "logout", :to => "sessions#destroy", :as => "logout"

  get '/escapes_lat_long', to: "escapes#escapes_lat_long"
end

app/models/escape.rb
class Escape < ActiveRecord::Base
  attr_accessible :location, :phone, :price,
                  :street, :title, :upvotes, :downvotes, :votes

  after_create :find_nearest_metro

  geocoded_by :address

  has_one :playlist

  def self.active
    where("expiration > ? OR expiration LIKE ?",
      Time.now.strftime("%B %d, %Y").to_date, "")
  end

  def find_nearest_metro
    0.upto(1500) do |mile_radius|
      metro = Metro.near([self.latitude, self.longitude], mile_radius)
      if metro.count == 1
        set_metro_value_as(metro)
      end
    end
  end

  def set_metro_value_as(metro)
    self.nearest_metro = metro.first.name
    self.save
  end

  def address
    "#{latitude} #{longitude}"
  end

  def city_escaped
    self.city.gsub(" ","_").gsub("-","_")
  end

  def votes
    vote_tally = self.upvotes - self.downvotes
    if vote_tally <= 1
      votes = 1
    elsif vote_tally >= 20
      votes = 20
    else
      votes = vote_tally
    end
  end

  def true_votes
    upvotes - downvotes
  end

  def add_vote
    self.upvotes += 1
    save
  end

  def add_downvote
    self.downvotes += 1
    save
  end
end

app/models/metro.rb
class Metro < ActiveRecord::Base
  attr_accessible :name, :country, :latitude, :longitude

  geocoded_by :address

  after_validation :geocode

  has_many :popular_songs
  has_many :unique_songs

  def address
    "#{self.name}, #{self.country}"
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :rdio_tracks
  belongs_to :escape

  def self.build_from_artist(artist, escape, recommender=Recommender)
    playlist = Playlist.find_or_create_by_escape_id(escape.id)
    playlist.rdio_tracks += recommender.recommend_tracks_from_artist(artist)
    playlist.save
    playlist
  end

end

app/models/popular_song.rb
class PopularSong < ActiveRecord::Base
  belongs_to :metro
end

app/models/rdio_track.rb
class RdioTrack < ActiveRecord::Base
  attr_accessible :artist, :title, :rdio_id
  belongs_to :playlist

end

app/models/recommender.rb
require 'nestling'

class Recommender < ActiveRecord::Base

  def self.recommend_tracks_from_artist(artist=artist, client=Nestling.new)
    playlist_rec = client.playlist.static(
      artist: artist,
      bucket: "id:rdio-us-streaming",
      type: "artist-radio",
      limit: true
     )
    parse_response(playlist_rec)
  end

  def self.parse_response(rec)
    rdio_tracks = []
    rec.each do |track|
      track = RdioTrack.new(
        artist: track[:artist_name],
        title: track[:title],
        rdio_id: track[:foreign_ids].first["foreign_id"].split(":").last
        )
      rdio_tracks << track
    end
    rdio_tracks
  end
end

app/models/unique_song.rb
class UniqueSong < ActiveRecord::Base
  belongs_to :metro

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth)
      where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :prepare_for_mobile

private

  def check_presence_of_current_user
    if current_user
      redirect_to escapes_path
    else
      redirect_to root_path unless request.fullpath == root_path
      flash[:notice] = "You must be signed in"
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :mobile_device?

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end

end

app/controllers/escape_picker_controller.rb
class EscapePickerController < ApplicationController

	def create
	  @escape = Escape.find(params[:escape_id])
	  redirect_to escape_path(@escape, :city => params[:city],
	  																 :state => params[:state])
	end

end

app/controllers/escapes_controller.rb
class EscapesController < ApplicationController
  before_filter :look_up_escape, :only => [:update, :show]

  def update
    if params[:upvotes]
      @escape.add_vote
    elsif params[:downvotes]
      @escape.add_downvote
    end
    respond_to do |format|
      format.js { }
    end
  end

  def index
    @location = request.location
    @escapes = Escape.active
  end

  def show
    @distance = @escape.distance_to(params[:city],params[:state])
    @metro = Metro.find_by_name(@escape.nearest_metro)
    if @metro.unique_songs != []
      @artist = @metro.unique_songs.first.artist
      @playlist = @escape.playlist && @escape.playlist.rdio_tracks.any? ?
                @escape.playlist : Playlist.build_from_artist(@artist, @escape)
    end
  end

  def escapes_lat_long
    render json: Escape.all.map{ |escape| { :title     => escape.title,
                                            :price     => escape.price,
                                            :city      => escape.city_escaped,
                                            :state     => escape.state,
                                            :latitude  => escape.latitude,
                                            :longitude => escape.longitude,
                                            :votes     => escape.votes } }
  end

private
  def look_up_escape
    @escape = Escape.find(params[:id])
  end
  
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def shoutouts
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :check_presence_of_current_user, :only => :new

  def new
  end

  def create
  user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to escapes_path, notice: "Signed in."
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/escapes_helper.rb
module EscapesHelper
	def playback_token_tag
    if Rails.env.production?
    	tag('meta', name: 'playback_token', content: RDIO.getPlaybackToken(domain: "rdtrip.in"))
    else
    	tag('meta', name: 'playback_token', content: RDIO.getPlaybackToken(domain: "localhost"))
    end
  end

  def yahoo_id_tag
  	if Rails.env.production?
  		tag('meta', name: 'yahoo_id', content: ENV['YAHOO_GEO_ID'])
  	else
  		tag('meta', name: 'yahoo_id', content: YAHOO_GEO_ID)
  	end
  end

end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/escapes/index.html.erb
<%= content_for(:header) do %>
  <%= yahoo_id_tag %>
  <script type="text/javascript">
    $(function(){
      $(".chzn-select").chosen()
    });
    $(function(){
      $("#escape_id_chzn").addClass("field");
    });
    $(function(){
      $(document).ready(initiate_geolocation);
    });
    $(function(){  
      $("#geo").click(initiate_geolocation);  
    });
    function initiate_geolocation() {  
      navigator.geolocation.getCurrentPosition(handle_geolocation_query);  
    }  

    function handle_geolocation_query(position){
      var yahooID = $("meta[name=yahoo_id]").attr('content');
      $.get('http://where.yahooapis.com/geocode?location=' + position.coords.latitude + ',+' + position.coords.longitude + '&gflags=R&J&appid=' + yahooID, function(data){
        var xml = data;
        var city = $(xml).find("city").text();
        var state = $(xml).find("statecode").text();
        $('span#city').text(city);
        $('span#state').text(state);
        $('.field:first').append('<input id="city" name="city" type="hidden" value="' + city + '" />');
        $('.field:first').append('<input id="state" name="state" type="hidden" value="' + state + '" />');
      });
    }
  </script>
<% end %>

<div id="escape_select">
  <%= form_tag url_for("/escape_picker"), :method => 'post', :id => "escape_selector" do %>
    <div>
      <h1>Set your Escape to some music</h1>
    </div>
    <div class="field">
      <p class="label">Current location <%= link_to image_tag("geo.png", :id => "geo"), "#", :id => "geo" %></p>
      <p id="current_location"><span id="city"></span>, <span id="state"></span>
    </div>
    <div class="field">
      <p class="label">Your escape</p>
      <%= select_tag "escape_id", options_for_select([["Choose your escape", ""]]+ Escape.active.collect {|escape| [ escape.title, escape.id ] }), :class=>'chzn-select', :data => { :placeholder => "Find escapes!" } %>
    </div>
    <div class="field">
      <%= button_tag "GO", :type => :submit, :id => "submit_form" %>
    </div>
  <% end %>
</div>

app/views/escapes/index.mobile.erb
<%= content_for(:header) do %>
  <script type="text/javascript">
    $(function(){
      $("#escape_id_chzn").addClass("field");
    });
  </script>
<% end %>

<div id="escape_select">
  <%= form_tag url_for("/escape_picker"), :method => 'post', :id => "escape_selector" do %>
    <div>
      <h1>Set your Escape to some music:</h1>
    </div>
    <div class="field">
      <p class="label">Current location:</p>
      <%= hidden_field_tag "city", @location.city %>
      <%= hidden_field_tag "state", @location.state %>
      <p id="current_location"><%= @location.city %>, <%= @location.state %></p>
    </div>
    <div class="field">
      <p class="label">Your escape:</p>
      <%= select_tag "escape_id", options_for_select([["Choose your escape", ""]]+ Escape.active.collect {|escape| [ escape.title, escape.id ] }), :class=>'chzn-select', :data => { :placeholder => "Find escapes!" } %>
    </div>
    <div class="field">
      <%= button_tag "GO", :type => :submit, :id => "submit_form" %>
    </div>
  <% end %>
</div>

app/views/escapes/show.html.erb
<%= content_for(:header) do %>
  <script type="text/javascript">
    $(function(){
      $('#pop_drop').click(function(){
        $('.popular').slideToggle();
      });
    });
    $(function(){
      var count = parseInt($("#vote_count").text());
      $('#upvote').click(function(){
        count += 1;
        $('#vote_count').text(count);
      });
      $('#downvote').click(function(){
        count -= 1;
        $('#vote_count').text(count);
      });
    });
  </script>
  <%= playback_token_tag %>
<% end %>
<div id="escape_info">
  <h1><%= @escape.title %></h1>
  <p><%= @escape.location %>, <%= @escape.price %><span id="details"><%= link_to "Full Details", "#", :title => "#{@escape.details}" %></span></p>
  <% if @distance.nan? %>
    <p><%= @escape.street %> &bull; <%= @escape.city %>, <%= @escape.state %></p>
  <% else %>
    <p><%= @escape.street %> &bull; <%= @escape.city %>, <%= @escape.state %> &bull; <%= @distance.round %> miles away</p>
  <% end %>
</div>
<div id="music" class="group">
  <div id="lastfm_results">
    <p>Here are some songs Last.fm users from <%= @metro.name %> like to listen to. Browse while you listen to the rdio playlist on the right:</p>
    <div class="songs unique">
      <table>
        <thead>
          <tr>
            <th>Artist</th>
            <th>Song</th>
          </tr>
        </thead>
        <tbody>
          <% @metro.unique_songs.each do |song| %>
          <tr>
            <td><%= song.artist %></td>
            <td><%= link_to song.title, song.url, :target => "_blank", :class => "lastfm-link" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <p>Too underground? <%= link_to "Click here", "#", :id => "pop_drop" %> for the popular songs from <%= @metro.name %>
    <div class="songs popular">
      <table>
        <thead>
          <tr>
            <th>Artist</th>
            <th>Song</th>
          </tr>
        </thead>
        <tbody>
          <% @metro.popular_songs.each do |song| %>
          <tr>
            <td><%= song.artist %></td>
            <td><%= link_to song.title, song.url, :target => "_blank", :class => "lastfm-link" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div id="rdio_playlist">
  <% if current_user && @metro.unique_songs != [] %>
    <%= content_tag "div", :id => "tracks", :data => {:tracks => @playlist.rdio_tracks } do %>
    <% end %>
    <div id="api">
    </div>
    <div id="current_track">
      <table id="playing">
        <tbody>
          <tr>
            <td class="play-label">Artist:</td>
            <td><span id="artist"></span></td>
          </tr>
          <tr>
            <td class="play-label">Title:</td>
            <td><span id="track"></span></td>
          </tr>
        </tbody>
      </table>
      <div id="controls">
        <%= link_to image_tag("previous.png"), "#", :id => "previous" %>
        <%= link_to image_tag("play.png"), "#", :id => "play" %>
        <%= link_to image_tag("pause.png"), "#", :id => "pause" %>
        <%= link_to image_tag("next.png"), "#", :id => "next" %>
      </div>
    </div>
    <div id="votes">
      <%= link_to image_tag("love.png"), escape_path(@escape, :upvotes => true), :id => "upvote", :method => :put, :remote => true %>
      <%= link_to image_tag("dislike.png"), escape_path(@escape, :downvotes => true), :id => "downvote", :method => :put, :remote => true %>
      <h4 id="vote_count">Popularity: <%= @escape.true_votes %></h4>
    </div>
  </div>
  <% else %>
  <p>Log in for some playlists!</p>
  <% end %>
</div>

app/views/escapes/show.mobile.erb
<%= content_for(:header) do %>
  <script type="text/javascript">
    $(function(){
      $('#pop_drop').click(function(){
        $('.popular').slideToggle();
      });
    });
  </script>
<% end %>
<div id="escape_info">
  <h2><%= @escape.title %></h2>
  <p><%= @escape.location %>, <%= @escape.price %><span id="details"><%= link_to "Full Details", "#", :title => "#{@escape.details}" %></span></p>
  <p><%= @escape.street %></p>
  <p><%= @escape.city %>, <%= @escape.state %> &bull; <%= @distance.round %> miles away</p>
</div>
<div id="music" class="group">
  <div id="lastfm_results">
    <p>Here are some songs Last.fm users from <%= @metro.name %> like to listen to. Browse while you listen to the rdio playlist on the right:</p>
    <div class="songs unique">
      <table>
        <thead>
          <tr>
            <th>Artist</th>
            <th>Song</th>
          </tr>
        </thead>
        <tbody>
          <% @metro.unique_songs.each do |song| %>
          <tr>
            <td><%= song.artist %></td>
            <td><%= link_to song.title, song.url, :target => "_blank", :class => "lastfm-link" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/escapes/update.js.erb
$('#upvote a').removeAttr('href');

app/views/info/shoutouts.html.erb
<h1>Shout outs</h1>
<p>A special thank you to the following people: (in no particular order)</p>
<ul>
	<li>Matt Robinson</li>
	<li>Mike Chlipala</li>
	<li>Austen Ito</li>
	<li>Mike Silvis</li>
	<li>Horace Williams</li>
	<li>Tom Kiefhaber</li>
	<li>Chris Anderson</li>
	<li>Chris Maddox</li>
</ul>

app/views/info/shoutouts.mobile.erb
<h1>Shout outs</h1>
<p>A special thank you to the following people:</p>
<ul>
	<li>Mike Chlipala</li>
	<li>Austen Ito</li>
	<li>Matt Robinson</li>
	<li>Mike Silvis</li>
	<li>Horace Williams</li>
	<li>Tom Kiefhaber</li>
	<li>Chris Anderson</li>
</ul>

app/views/layouts/_logged_in.html.erb
<div id="logo"><a href="/">rdtrip</a></div>
<div id="login">
	<ul>
		<li id="user_image">
			<% if current_user.image %>
				<%= image_tag(current_user.image) %>
			<% end %>
		</li>
		<li class="text">
			<%= current_user.name %>
		</li>
		<li class="divider">
		</li>
		<li class="text">
			<%= link_to "Log out", logout_path %>
		</li>
	</ul>
</div>

app/views/layouts/_logged_out.html.erb
<div id="logo"><a href="/">rdtrip</a></div>
<div id="login">
	<p><%= link_to image_tag("js-signin.png"), "/auth/linkedin", :id => "oauth_linkedin" %></p>
</div>

app/views/layouts/_mobile_in.mobile.erb
<div id="logo"><a href="/">rdtrip</a></div>
<div id="login">
	<ul>
		<li id="user_image">
			<%= image_tag(current_user.image) %>
		</li>
		<li class="divider">
		</li>
		<li class="text">
			<%= link_to "Log out", logout_path %>
		</li>
	</ul>
</div>

app/views/layouts/_mobile_out.mobile.erb
<div id="logo"><a href="/">rdtrip</a></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rdtrip</title>
  <%= stylesheet_link_tag    'application', :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Lilita+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application' %>
  <%= yield(:header) %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div id="header_content">
    <% if current_user %>
      <%= render "layouts/logged_in" %>
    <% else %>
      <%= render "layouts/logged_out" %>
    <% end %>
    </div>
  </header>
  <div class="container group">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class => "flash-#{name}" if msg.is_a?(String) %>
    <% end %>
    <div id="content">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div id="inner">
      <div id="footer_content">
        <%= link_to "Shout outs", shoutouts_path %>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>rdtrip</title>
  <%= stylesheet_link_tag    'mobile', :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Lilita+One' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', :content_type => 'application/javascript' %>
  <%= yield(:header) %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="user-scalable=no,width=device-width"></meta>
</head>
<body>
  <header>
    <div id="header_content">
    <% if current_user %>
      <%= render "layouts/mobile_in" %>
    <% else %>
      <%= render "layouts/mobile_out" %>
    <% end %>
    </div>
  </header>
  <div class="container group">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class => "flash-#{name}" if msg.is_a?(String) %>
    <% end %>
    <div id="content">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div id="inner">
      <div id="footer_content">
        <%= link_to "Shout outs", shoutouts_path %>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/songs/index.html.erb
<h2><%= @escape.title %></h2>
<p>Here are some songs Last.fm users from <%= @metro.name %> like to listen to to make your roadtrip more personal:</p>
<div class="songs">
  <table>
    <thead>
      <tr>
        <th>Artist</th>
        <th>Song</th>
      </tr>
    </thead>
    <tbody>
      <% @metro.unique_songs.each do |song| %>
      <tr>
        <td><%= song.artist %></td>
        <td><%= link_to song.title, song.url, :target => "_blank" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<p>Too underground for you? Here are the popular songs Last.fm users from <%= @metro.name %> are liking:
<div class="songs">
  <table>
    <thead>
      <tr>
        <th>Artist</th>
        <th>Song</th>
      </tr>
    </thead>
    <tbody>
      <% @metro.popular_songs.each do |song| %>
      <tr>
        <td><%= song.artist %></td>
        <td><%= link_to song.title, song.url, :target => "_blank" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>